version: '3.8'

services:
  backend:
    image: legit0302/be:1.0.20  # 도커 허브에 있는 최신 백엔드 이미지
    container_name: backend
    restart: always
    ports:
      - '8000:8000'
    networks:
      - app-network

  frontend:
    image: legit0302/fe:1.0.5  # 도커 허브에 있는 최신 프론트엔드 이미지
    container_name: frontend
    ports:
      - "5173:5173"
    command: yarn dev --host
    restart: always
    networks:
      - app-network

  daphne:
    image: legit0302/be:1.0.20  # 백엔드와 동일함
    container_name: daphne
    restart: always
    ports:
      - '8001:8001'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /home/ec2-user/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - daphne
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
