services:
  backend:
    image: legit0302/be:1.0.19 # 배포: 태그를 계속 수정하면서 push
    container_name: backend
    restart: always
    ports:
      - '8000:8000'
    networks:
      - app-network

  frontend:
    image: legit0302/fe:1.0.5 # 배포: 태그를 계속 수정하면서 push
    container_name: front
    ports:
      - "5173:5173"
    command: yarn dev --host
    restart: always
    networks:
      - app-network

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./staticfiles:/app/staticfiles
#      - /etc/letsencrypt:/etc/letsencrypt
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - backend
#      - frontend
#    certbot:
#      image: certbot/certbot
#      user: root
#      volumes:
#        - /etc/letsencrypt:/etc/letsencrypt
#        - /var/www/certbot:/var/www/certbot
#      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#      depends_on:
#        - nginx
#      ports:
#        - "6380:6380"

networks:
  app-network:
    driver: bridge